### ISSUE TITLE
list assignment index out of range

### ISSUE THREAD

**Issue by tomStegmaier** [steinhkl/tsgce#14]
Hey, 
could someone help me with that Problem?

For:"this are a test sentence."
```
Exception happened during processing of request from ('127.0.0.1', 38696)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./webserver.py", line 57, in do_POST
    result1 = start.main(sentence)
  File "/home/tom/workspace/nlp/project/tsgce/start.py", line 24, in main
    jsong2 = tagandroll.main(jsong1)
  File "/home/tom/workspace/nlp/project/tsgce/tagandroll.py", line 146, in main
    injson["forms"] = genlist(injson)
  File "/home/tom/workspace/nlp/project/tsgce/tagandroll.py", line 125, in genlist
    out.extend(permutengrams(jsonsentence))
  File "/home/tom/workspace/nlp/project/tsgce/tagandroll.py", line 109, in permutengrams
    tmp_tok_sent[i] = swappedword
IndexError: list assignment index out of range
```

other Example
For: "the dog barks of the cat."

```
Exception happened during processing of request from ('127.0.0.1', 38578)
Traceback (most recent call last):
  File "/home/tom/workspace/nlp/project/tsgce/biggercorpora.py", line 37, in parsegooglehtml
    result = int(res.text.replace(".", "").split()[1])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./webserver.py", line 57, in do_POST
    result1 = start.main(sentence)
  File "/home/tom/workspace/nlp/project/tsgce/start.py", line 39, in main
    listofsentences = biggercorpora.main(listwithoutduplicates)
  File "/home/tom/workspace/nlp/project/tsgce/biggercorpora.py", line 71, in main
    parsehtmlresults[sentence] = parsegooglehtml(sentence)
  File "/home/tom/workspace/nlp/project/tsgce/biggercorpora.py", line 40, in parsegooglehtml
    result = int(res.text.replace(".", "").split()[0])
IndexError: list index out of range
```

**Comment by steinhkl** [comment]
This is because the shuffle function shuffles punctuation. That should (IMO) not be the case.
With the most recent comit f3e7e54 this was temporarely disabled.

**Comment by humpalum** [comment]
Oh dang. Will fix ist asap
